"""Feature 10 — the verified summary export.

Markdown rather than a rendered PDF or image card. Three reasons: it needs no
extra dependency, it pastes straight into notes/Slack/a doc, and — the one that
decides it — the verification badge survives as *text*. A PNG card would carry
the badge as a coloured glyph that a screen reader cannot read and a greyscale
copy cannot distinguish, which would quietly undo the accessibility care taken
everywhere else in the UI.

Every claim exports with its status, its match score, its page, and its quote, so
the artefact is auditable away from the app.
"""

from __future__ import annotations

from datetime import date

from integration.contracts import Brief, Document
from ui.theme import STATUS_STYLES

#: Text markers, chosen so the status is unambiguous in a plain-text context.
_MARKERS = {
    "verified": "[VERIFIED]",
    "paraphrased": "[PARAPHRASED]",
    "unsupported": "[UNSUPPORTED]",
    "unverified": "[NOT VERIFIED]",
}


def summary_markdown(doc: Document, brief: Brief) -> str:
    """Render the brief as a self-contained, auditable Markdown document."""
    lines: list[str] = [
        f"# {doc.title or 'Verified summary'}",
        "",
        f"_Verified summary generated by PaperLens on {date.today().isoformat()}._",
        "",
    ]

    tally = brief.tally()
    summary_bits = [
        f"{count} {STATUS_STYLES[status].label.lower()}"
        for status, count in tally.items()
        if count
    ]
    if summary_bits:
        lines += [f"**Evidence:** {' · '.join(summary_bits)}", ""]

    if doc.page_count:
        lines += [f"**Source:** {doc.page_count} pages", ""]

    lines += [
        "Each claim below was checked against the extracted text of the page it cites.",
        "Match scores are fuzzy-match similarity between the quoted text and the page.",
        "",
        "---",
        "",
    ]

    for section, claims in brief.by_section().items():
        lines += [f"## {section}", ""]
        for claim in claims:
            evidence = claim.evidence
            marker = _MARKERS.get(evidence.status, "[NOT VERIFIED]")
            score = "" if evidence.score is None else f" · match {evidence.score:.2f}"
            page = "" if evidence.page is None else f" · p.{evidence.page}"

            lines += [f"- **{marker}**{page}{score}", f"  {claim.text}"]
            if evidence.has_quote:
                quote = evidence.quote.strip().strip('"')
                lines += ["", f"  > {quote}"]
            lines.append("")

    unsupported = tally.get("unsupported", 0)
    if unsupported:
        lines += [
            "---",
            "",
            f"> **Caution:** {unsupported} claim{'s' if unsupported > 1 else ''} in this "
            "summary could not be located in the source paper and should not be relied on.",
            "",
        ]

    return "\n".join(lines)
